name: CI
on:
  push:
  workflow_dispatch:
jobs:
  depkoyment:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        
      - name: Login no Docker Hub
        uses: actions-hub/docker/login@master
        env:         
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: $DOCKER_USERNAME/app:latest
